from distutils.core import setup
setup(
  name = 'espandas',
  packages = ['espandas'],
  version = '1.0.1',
  description = 'Insert and Extract Pandas DataFrames with ElasticSearch',
  author = 'David Shaub',
  author_email = 'davidshaub@gmx.com',
  url = 'https://github.com/dashaub/espandas',
  download_url = 'https://github.com/dashaub/espandas/archive/1.0.1.tar.gz',
  keywords = ['ElasticSearch', 'pandas', 'nosql'],
  classifiers = ['Development Status :: 4 - Beta',
                 'Environment :: Console',
                 'Intended Audience :: Developers',
                 'Intended Audience :: Science/Research',
                 'License :: OSI Approved :: GNU General Public License v3 (GPLv3)',
                 'Natural Language :: English',
                 'Operating System :: OS Independent',
                 'Programming Language :: Python :: 2',
                 'Programming Language :: Python :: 2.7',
                 'Programming Language :: Python :: 3',
                 'Programming Language :: Python :: 3.4',
                 'Programming Language :: Python :: 3.5',
                 'Programming Language :: Python :: 3.6',
                 'Topic :: Database',
                 'Topic :: Scientific/Engineering'],
)
